#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mosh
Version  : 1.2.5
Release  : 3
URL      : https://mosh.mit.edu/mosh-1.2.5.tar.gz
Source0  : https://mosh.mit.edu/mosh-1.2.5.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: mosh-bin
Requires: mosh-doc
BuildRequires : pkgconfig(bash-completion)
BuildRequires : pkgconfig(openssl)
BuildRequires : pkgconfig(protobuf)
BuildRequires : pkgconfig(tinfo)
BuildRequires : zlib
BuildRequires : zlib-dev

%description
Mosh: the mobile shell
======================
Mosh is a remote terminal application that supports intermittent
connectivity, allows roaming, and provides speculative local echo
and line editing of user keystrokes.

%package bin
Summary: bin components for the mosh package.
Group: Binaries

%description bin
bin components for the mosh package.


%package doc
Summary: doc components for the mosh package.
Group: Documentation

%description doc
doc components for the mosh package.


%prep
%setup -q -n mosh-1.2.5

%build
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/mosh
/usr/bin/mosh-client
/usr/bin/mosh-server

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
